apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ipa-tuura
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipa-tuura
    app.kubernetes.io/part-of: ipa-tuura
  name: ipa-tuura
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: ipa-tuura
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: ipa-tuura
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ipaidm-tenant/ipa-tuura/ipa-tuura@sha256:f4df3eec32919d53608f4f50cecbf4e5625a011ca53a0f31abe56b08233694c9
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
