apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ipa-tuura
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ipaidm-tenant/ipa-tuura/ipa-tuura@sha256:c9ffc17ea8a73476ac643c38b171c59c27b7cbc5e1053a02e2dd6d2e18b989ef
        name: my-python
        resources: {}
status: {}
