apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ipa-tuura
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ipaidm-tenant/ipa-tuura/ipa-tuura@sha256:d1c9cb06c89ee758df4c6a3c1e8472d83af695c7fd430e4c82f5260ce3e3f942
        name: my-python
        resources: {}
status: {}
