apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ipa-tuura
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ipaidm-tenant/ipa-tuura/ipa-tuura@sha256:184e4f7bffdfb090e3222d9042da95b2f2f9025cfc66bbcd4faf27f28ccadd21
        name: my-python
        resources: {}
status: {}
