apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ipa-tuura
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipa-tuura
    app.kubernetes.io/part-of: ipa-tuura
  name: ipa-tuuravoop
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ipa-tuura
    weight: null
status: {}
